package com.neuedu.dao;

import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfo record);

    /**
     * 登录  用户名是否存在
     * */
    int checkUsername(String username);

    /**
     * 效验邮箱是否存在
     * */
    int checkEmail(String email);

    /**
     * 根据用户名和密码进行查询，是否存在这个用户
     * */
    UserInfo selectUserByUsernameAndPassword(@Param("username") String username,@Param("password") String password);
/**
 * 根据username查询密保问题
 * */
    String selectQuestionByusername(String username);
/**
 * 查询答案
 * */
int checkAnswerByUsernameQuestion(@Param("username") String username,
                                  @Param("question") String question,
                                  @Param("answer") String answer);
//更具用户名更新密码
    int updatePasswordByusername(@Param("username") String username,
                                 @Param("passwordNew") String passwordNew);








}